title: Lukáš Lalinský
description: Random notes and stuff
url: http://oxygene.sk

permalink: /:year/:month/:title
markdown: rdiscount
exclude:
 - Makefile

category_dir: category
tag_dir: tag

disqus_shortname: oxygene

