title: Lukáš Lalinský
description: Random notes and stuff
url: http://oxygene.sk

permalink: /:year/:month/:title/
markdown: rdiscount
pygments: true
exclude:
 - Makefile

category_dir: category
tag_dir: tag

disqus_shortname: oxygene

category_names:
 acoustid: AcoustID
 database-modeller: Database Modeller
 musicbrainz: MusicBrainz
 programming: Programming
 taglib: TagLib
 tools: Tools

category_order:
 - acoustid
 - database-modeller
 - musicbrainz
 - programming
 - taglib
 - tools
